### ISSUE TITLE
Addable and editable sectors

### ISSUE THREAD

**Issue by synchronizedwritersblock** [to-boldly-go/tbg-deployment-planner#18]
Perhaps the most important missing feature would be the ability to change the available sectors (or ship containers since that's basically want a sector needs to be). Most important for regular deployment with uncertain number of task forces - one player might create 4 task forces and the other 6 different task forces and both of those need to be available in the same vote. Similarly we often add entire sectors mid-year.

**Comment by OnAGravitasHunt** [comment]
Need a sector adder/editor:
- [ ] Name
- [ ] Theater
- [ ] Type (core, border, TF etc.)
- [ ] Supporters
- [ ] List of major worlds (council seats perhaps?)
- [ ] Important stats for summary?
